### ISSUE TITLE
Icon tool bar too dark

### ISSUE THREAD

**Issue by m21-cerutti** [Toinane/colorpicker#84] opened 2020-07-27 18:08 UTC
![image](https://user-images.githubusercontent.com/23432929/88575846-cafaa980-d044-11ea-805f-474d76494ce4.png)

 I can't see Icon on black minimize.

**Comment by Toinane** [comment] 2020-07-27 19:11
Hey @m21-cerutti thank you for your issue, but it's a duplicate of #48 👍

**Closed by Toinane** 2020-07-27 19:11 UTC
Labels: Feature

**Comment by m21-cerutti** [comment] 2020-07-27 20:28
Ok sorry for that ^^.

**Comment by Toinane** [comment] 2020-07-27 20:36
no worries 😄
