### ISSUE TITLE
Doesn't work on Ubuntu 21.10

### ISSUE THREAD

**Issue by elec60** [Toinane/colorpicker#113] opened 2021-10-26 22:40 UTC
**Describe the bug**
Doesn't work on Ubuntu 21.10 #113

**OS (please complete the following information):**
 - OS: [Ubuntu 21.10]

**Comment by darkRaspberry** [comment] 2021-11-21 19:04
This is due to wayland. Currently colorpicker doesn't support wayland and only support xorg. 

Moreover, IF you bug is same as https://github.com/Toinane/colorpicker/issues/106 Please close Your bug.

**Comment by Toinane** [comment] 2021-11-23 15:56
duplicate of #106 thanks!

**Closed by Toinane** 2021-11-23 15:56 UTC
